creamery/config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :employees
  resources :stores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

creamery/app/models/assignment.rb
class Assignment < ApplicationRecord
    
    belongs_to :store
    belongs_to :employee
    
    before_save :end_previous_assignment
    
    validates :employee, presence: true, on: :create
    validates :store, presence: true, on: :create
    validate :active_store, on: :create
    validate :active_employee, on: :create
    validates :employee_id, :store_id, :start_date, :pay_level, presence: true
    validates_date :start_date, on_or_before: lambda { Date.current }
    validates_date :end_date, on_or_after: lambda { self.start_date }, message: "End date before start date" 
    
    def active_store
        s = Store.find_by_id(store_id)
        if s == nil
            errors.add(:store_id, "doesn't exist")
        else
            errors.add(:store_id, "is not active") unless s.active?
        end
    end
    
    def active_employee
        s = Employee.find_by_id(employee_id)
        if s == nil
            errors.add(:employee_id, "doesn't exist")
        else
            errors.add(:employee_id, "is not active") unless s.active?
        end
    end
    
    scope :current, -> { where("end_date > ?", Date.current) }
    scope :past, -> { where("end_date <= ?", Date.current) }
    scope :for_store, -> (store_id = nil){ where("store_id == ?", store_id)}
    scope :for_employee, -> (employee_id = nil){ where("employee_id == ?", employee_id)}
    scope :for_pay_level, -> (pay_level = nil){ where("pay_level == ?", pay_level)}
    scope :chronological, -> { order("start_date DESC") }
    scope :by_store, -> { order ("store_id") }
    scope :for_role, -> (role = nil){ joins(:employee).where("role == ?", role) }
    scope :by_employee, -> (last = nil, first = nil){ joins(:employee).order("last_name").where("last_name == ?", last).order("first_name").where("first_name == ?", first) }
    
    def end_previous_assignment
        cur_assignment = Assignment.for_employee(self.employee_id).current.first
        if (cur_assignment != id) and (cur_assignment.id != id)
            cur_assignment.update_attribute(:end_date, start_date)
            cur_assignment.save!
        end
    end

end

creamery/app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:store_id, :employee_id, :start_date, :end_date, :pay_level)
    end
end

creamery/app/helpers/assignments_helper.rb
module AssignmentsHelper
end

creamery/app/views/assignments/_form.html.erb
<%= form_for(assignment) do |f| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_id %>
    <%= f.number_field :store_id %>
  </div>

  <div class="field">
    <%= f.label :employee_id %>
    <%= f.number_field :employee_id %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, {prompt: { day: 'Day', month: 'Month', year: 'Year' },  
                                    start_year: Date.today.year, end_year: Date.today.year - 50}%>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, {prompt: { day: 'Day', month: 'Month', year: 'Year' },  
                                  start_year: Date.today.year + 20, end_year: Date.today.year - 50}%>
  </div>

  <div class="field">
    <%= f.label :pay_level %>
    <%= f.select :pay_level, [1,2,3,4,5,6]%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

creamery/app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

creamery/app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Employee</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Pay level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.store_id %></td>
        <td><%= assignment.employee_id %></td>
        <td><%= assignment.start_date %></td>
        <td><%= assignment.end_date %></td>
        <td><%= assignment.pay_level %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

creamery/app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

creamery/app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @assignment.store_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @assignment.employee_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @assignment.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @assignment.end_date %>
</p>

<p>
  <strong>Pay level:</strong>
  <%= @assignment.pay_level %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>